global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'trademaster'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # TradeMaster Trading Service
  - job_name: 'trading-service'
    static_configs:
      - targets: ['trading-service:8083']
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    scrape_timeout: 9s
    honor_labels: true
    params:
      format: ['prometheus']

  # Kubernetes pods with prometheus.io annotations
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - trademaster
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # PostgreSQL monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis monitoring
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Kafka monitoring
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s
    scrape_timeout: 10s

  # JVM monitoring
  - job_name: 'jvm-metrics'
    static_configs:
      - targets: ['trading-service:8083']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    params:
      format: ['prometheus']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'jvm_.*'
        target_label: __name__
        replacement: ${1}

  # Application-specific metrics
  - job_name: 'trading-business-metrics'
    static_configs:
      - targets: ['trading-service:8083']
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    params:
      format: ['prometheus']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'trading_.*'
        target_label: __name__
        replacement: ${1}

  # Health check monitoring
  - job_name: 'health-checks'
    static_configs:
      - targets: ['trading-service:8083']
    metrics_path: /actuator/health
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s