apiVersion: v1
kind: Namespace
metadata:
  name: trademaster
  labels:
    name: trademaster
    environment: production
    app.kubernetes.io/name: trademaster
    app.kubernetes.io/version: "2.0.0"
  annotations:
    kubernetes.io/managed-by: "kubectl"
    trademaster.com/team: "platform-engineering"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: trademaster-quota
  namespace: trademaster
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "20"
    services: "20"
    secrets: "50"
    configmaps: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: trademaster-limits
  namespace: trademaster
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container