apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    orgId: 1
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 30s
    secureJsonFields:
      httpHeaderValue1: false
    version: 1

  - name: TradeMaster-Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
    orgId: 1
    uid: trademaster_prometheus
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger_uid
          urlDisplayLabel: View in Jaeger
    secureJsonFields:
      httpHeaderValue1: false
    version: 1